[package]
name = "map_attr"
version = "0.1.0"
authors = ["museun <museun@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_macro = { path = "./my_macro" }
